site_name: git-studies
site_url: https://github.com/augustoliks/git-studies
site_description: Material de estudos Git
site_author: Carlos Neto | @augustoliks
repo_name: augustoliks/git-studies
repo_url: https://github.com/augustoliks/git-studies
# edit_uri: ''

nav:
  - index: about.md
  - Git:
    - git/about.md
    - git/comandos.md
  - Workflows: 
    - workflows/about.md
    - workflows/git-flow.md
    - workflows/github-flow.md
    - workflows/gitlab-flow.md
  - Plataformas: 
    - plataformas/about.md
    - plataformas/github.md
    - plataformas/gitlab.md

theme:
  language: pt
  name: material
  logo: git-logo.svg
  favicon: git-logo.svg
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Light Mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Dark Mode
  features:
    - search.suggest
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/augustoliks
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c-neto

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
