site_name: git-mini-book
site_url: https://github.com/augustoliks/git-mini-book
site_description: Material de estudos Git
site_author: Carlos Neto | @augustoliks
repo_name: augustoliks/git-mini-book
repo_url: https://github.com/augustoliks/git-mini-book
edit_uri: ''

nav:
  - Git:
    - Conceitos: git/about.md
    - CLI: 
      - git/cli.md
      - Configuração: git/cli-config.md
      - Mudança de Estados: git/cli-state.md
      - Ramificações: git/cli-branch.md
      - Operações Remotas: git/cli-remote.md
      - Consultas: git/cli-logs.md
  - Workflows: 
    - workflows/about.md
    - workflows/git-flow.md
    - workflows/github-flow.md
    - workflows/gitlab-flow.md
  - Plataformas: 
    - plataformas/about.md
    - plataformas/github.md
    - plataformas/gitlab.md

theme:
  language: pt
  name: material
  logo: git-logo.svg
  favicon: git-logo.svg
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Dark Mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Light Mode
  features:
    - search.suggest
    - search.highlight
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/augustoliks
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c-neto

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
